apiVersion: v1
kind: ConfigMap
metadata:
  name: app-code
  namespace: demo
data:
  index.php: |
    <?php
    $dbhost = getenv('DB_HOST') ?: 'mysql';
    $dbuser = getenv('DB_USER') ?: 'demo_user';
    $dbpass = getenv('DB_PASS') ?: 'demopass';
    $dbname = getenv('DB_NAME') ?: 'demo_db';
    echo "<h1>Hello from PHP-FPM on Kubernetes</h1>";
    echo "<p>DB host: $dbhost</p>";
    echo "<p>Try connecting to DB (this is demo, no PDO check)</p>";
  static-index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to Kubernetes Demo App</title>
    </head>
    <body>
        <h1>Welcome to the Kubernetes Demo Application!</h1>
        <p>This is a simple static HTML page served from a ConfigMap.</p>
    </body>
    </html>