apiVersion: v1
kind: Deployment
metadata:
  name: php
  namespace: demo
spec:
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: php:8.1-cli
          command: ["sh", "-c", "while true; do echo 'php worker running'; sleep 60; done"]
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE"
---
apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: demo
spec:
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: ClusterIP