apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  namespace: demo
spec:
  selector:
    matchLabels:
      app: php-fpm
  replicas: 2
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
        - name: php-fpm
          image: php:8.1-fpm
          ports:
            - containerPort: 9000
          env:
            - name: DB_HOST
              value: "mysql"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
          volumeMounts:
            - name: www
              mountPath: /var/www/html
      volumes:
        - name: www
          configMap:
            name: app-code
            # mount all keys as files under /var/www/html
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  namespace: demo
spec:
  selector:
    app: php-fpm
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
  clusterIP: None
