apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: demo
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_USER: demo_user
  MYSQL_PASSWORD: demopassword
  MYSQL_DATABASE: demo_db